// SPDX-License-Identifier: Apache-2.0
package com.openinglab.service

import com.openinglab.shared.content.ContentManifest
import com.openinglab.shared.content.GameRecord
import com.openinglab.shared.content.OpeningRecord
import com.openinglab.shared.storage.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.encodeToString
import java.nio.file.Files
import java.nio.file.LinkOption.NOFOLLOW_LINKS
import java.nio.file.Path
import java.nio.file.StandardCopyOption.ATOMIC_MOVE

data class TrustedPack(val id: String, val manifestSha256: String, val directory: Path)
data class ValidatedPack(val descriptor: PackDescriptor, val openings: List<OpeningRecord>, val games: List<GameRecord>)

/** Local object storage implementation; clients may read hashes, never submit paths or source URLs. */
class PackObjects(private val root: Path, private val trusted: List<TrustedPack>) {
    init { Files.createDirectories(root); require(!Files.isSymbolicLink(root)); require(trusted.map { it.id }.distinct().size == trusted.size) }
    fun spec(id: String) = trusted.singleOrNull { it.id == id } ?: throw ApiFailure("PACK_NOT_ALLOWLISTED", 404)
    fun bundle(id: String): PackBundle {
        val pack = spec(id)
        require(hashPattern.matches(pack.manifestSha256))
        val manifest = bounded(pack.directory.resolve("manifest.json"), 65_536)
        require(contentSha256(manifest) == pack.manifestSha256)
        val parsed = codec.decodeFromString<ContentManifest>(manifest.decodeToString(throwOnInvalidSequence = true))
        require(parsed.packId == id && parsed.files.map { it.name }.toSet() == payloadNames && parsed.files.size == 4)
        require(parsed.files.all { it.bytes in 0..8_388_608 } && parsed.files.sumOf { it.bytes } <= 12_582_912)
        val files = parsed.files.associate { file -> file.name to bounded(pack.directory.resolve(file.name), file.bytes.toInt()).also {
            require(it.size.toLong() == file.bytes && contentSha256(it) == file.sha256)
        } }
        return PackBundle(manifest, files, pack.manifestSha256)
    }
    suspend fun validateAndStore(id: String): ValidatedPack = withContext(Dispatchers.IO) {
        // Reuse mobile's complete legal/provenance/count/dependency checks in an isolated temporary DB.
        // No learner database is opened. A failed validation never publishes PostgreSQL pointers.
        val work = Files.createTempDirectory(root, "validation-")
        val database = createJvmLearningDatabase(work.resolve("validation.db").toString())
        try {
            val store = RoomLearningStore(database)
            val visiting = mutableSetOf<String>(); val installed = mutableSetOf<String>()
            suspend fun install(packId: String) {
                if (packId in installed) return
                require(visiting.add(packId))
                val bytes = bundle(packId); val manifest = codec.decodeFromString<ContentManifest>(bytes.manifest.decodeToString())
                manifest.dependencies.forEach { dependency ->
                    require(spec(dependency.packId).manifestSha256 == dependency.manifestSha256); install(dependency.packId)
                }
                store.install(bytes); visiting.remove(packId); installed.add(packId)
            }
            install(id)
            val pack = requireNotNull(store.retainedPack(id))
            val bytes = bundle(id)
            val objects = root.resolve(pack.manifestSha256)
            Files.createDirectories(objects); require(!Files.isSymbolicLink(objects))
            (bytes.files + ("manifest.json" to bytes.manifest)).forEach { (name, value) ->
                val destination = objects.resolve(name)
                if (Files.exists(destination, NOFOLLOW_LINKS)) require(bounded(destination, value.size).contentEquals(value))
                else {
                    val temp = Files.createTempFile(objects, "staged-", ".partial")
                    try { Files.write(temp, value); Files.move(temp, destination, ATOMIC_MOVE) }
                    finally { Files.deleteIfExists(temp) }
                }
            }
            ValidatedPack(PackDescriptor(pack.manifestSha256, pack.manifest), store.openings(id), store.games(id))
        } finally {
            database.close()
            // These exact files are generated by the temporary validation DB above, not user data.
            listOf("validation.db", "validation.db-shm", "validation.db-wal", "validation.db-journal", "validation.db.lck").forEach { Files.deleteIfExists(work.resolve(it)) }
            Files.deleteIfExists(work)
        }
    }
    fun read(descriptor: PackDescriptor, name: String): Pair<ByteArray, String> {
        if (name !in payloadNames && name != "manifest.json") throw ApiFailure("FILE_NOT_FOUND", 404)
        val directory = root.resolve(descriptor.manifestSha256)
        require(!Files.isSymbolicLink(directory))
        val file = descriptor.manifest.files.singleOrNull { it.name == name }
        val limit = file?.bytes?.toInt() ?: 65_536
        val bytes = try { bounded(directory.resolve(name), limit) } catch (_: Exception) { throw ApiFailure("OBJECT_UNAVAILABLE", 503) }
        val expected = file?.sha256 ?: descriptor.manifestSha256
        if (contentSha256(bytes) != expected || (file != null && bytes.size.toLong() != file.bytes)) throw ApiFailure("OBJECT_INTEGRITY_FAILURE", 503)
        return bytes to expected
    }
    companion object {
        private val payloadNames = setOf("openings.jsonl", "games.jsonl", "issues.jsonl", "ATTRIBUTION.txt")
        private fun bounded(path: Path, limit: Int): ByteArray {
            require(Files.isRegularFile(path, NOFOLLOW_LINKS) && Files.size(path) <= limit)
            return Files.newInputStream(path, NOFOLLOW_LINKS).use { it.readNBytes(limit + 1).also { value -> require(value.size <= limit) } }
        }
        fun reviewed(root: Path): List<TrustedPack> = listOf(
            "lichess-openings-c67912be581f-import-v1" to "40d2ab2920dafa5c60ce163695c8e0e3fa31cf1cf922a285461aeafcb1f55dc3",
            "lichess-broadcast-2020-04-2020-04-snap-import-v1" to "cf50ffff258582121d7a8f4968ffd4cb60e10ba04ea1a8fa5eb69aa51947ffc7",
            "lichess-broadcast-2020-01-2020-01-snap-import-v1" to "98c81851574b0d94f43b8a382e6a92df19328db2b8ced7e48d5c25ab50ff4c63",
        ).map { (id, checksum) -> TrustedPack(id, checksum, root.resolve("content/packs").resolve(id)) }
    }
}
