# Variation introductions (IDEA claims: no move or square names allowed by the checker).
I = {}
def v(name, *sentences): I[name] = list(sentences)

# ---- Berlin ----
v("Berlin Defense", "Black develops the king's knight and attacks White's centre pawn at once instead of first questioning the bishop. It is one of the most solid defences at the top level and leads to very different games depending on how White protects the centre.")
v("Berlin Defense, Rio Gambit Accepted", "Black simply takes the centre pawn after White castles. White regains it by force, and the play splits into the queenless Berlin endgame and the rook-lift lines where White pressures Black's uncastled king along the open file.")
v("Berlin Defense, Anti-Berlin Variation", "White protects the centre pawn with a pawn and avoids the forcing endgame lines. The game stays complex with all pieces on the board; White aims for a slow build-up and a later central break, Black for active bishops and a solid centre.")
v("Berlin Defense, l'Hermet Variation", "Black's knight retreats instead of taking more material, inviting White to exchange on the queenside and open the centre. Most games lead to the famous queenless endgame where structure matters more than attack.")
v("Berlin Defense, l'Hermet Variation, Berlin Wall Defense", "The Berlin endgame: queens are off and Black's king has lost the right to castle, but Black has the bishop pair and a very solid position. White plays for the healthy kingside pawn majority; Black for activity of the bishops and patient defence.")
v("Berlin Defense, Berlin Wall", "A typical setup in the Berlin endgame where Black develops the light-squared bishop and brings the king towards the queenside. White tries to use space and the extra kingside pawn; Black aims to neutralise and later use the bishops.")
v("Open Berlin Defense, l'Hermet Variation", "White advances in the centre with tempo instead of exchanging on the queenside. Black's knights have to find new squares and Black usually returns material to complete development.")
v("Open Berlin Defense, Showalter Variation", "White keeps the light-squared bishop instead of exchanging it, accepting a slower development to keep more tension.")
v("Berlin Defense, Anti-Berlin Variation, Mortimer Variation", "Black re-routes the knight towards the kingside so that the c-pawn can support a later central advance. It is solid but slow, and White simply develops.")
v("Berlin Defense, Beverwijk Variation", "Black develops the dark-squared bishop actively and leaves the centre pawn to its fate for the moment. White can grab space in the centre with tempo.")
v("Berlin Defense, Improved Steinitz Defense", "Black protects the centre pawn with a pawn; solid but passive, it gives White a free hand to build the ideal centre.")

# ---- Exchange ----
v("Exchange Variation", "White gives up the Spanish bishop at once to change the pawn structure. Black gets the bishop pair and fast development; White gets a healthy kingside pawn majority that can become decisive in an endgame.")
v("Exchange Variation, Normal Variation", "White castles and keeps the option of opening the centre. Black usually protects the centre pawn and develops quickly to make the bishop pair count before the endgame.")
v("Exchange Variation, Alapin Gambit", "Black offers material to open lines towards White's king, using the bishop pair and active pieces. White must decide whether taking is worth the open files.")
v("Exchange Variation, Keres Variation", "White develops the queen's knight first to keep options open and support the centre before castling.")
v("Exchange Variation, Gligoric Variation", "Black protects the centre pawn with the f-pawn, a solid setup that keeps the bishop pair but slightly weakens the light squares near Black's king.")
v("Exchange Variation, King's Bishop Variation", "Black defends the centre pawn with the dark-squared bishop, developing quickly at the cost of a slightly passive bishop.")
v("Exchange Variation, Bronstein Variation", "Black protects the centre pawn with the queen and prepares to castle queenside, aiming for active piece play.")

# ---- Open ----
v("Open", "Black takes White's centre pawn and keeps it for the moment, accepting an open, dynamic position. Black gets free piece play; White targets the slightly loose black centre and the uncastled king.")
v("Open, Main Line", "Both sides follow the classical setup: Black supports the knight in the centre and develops the light-squared bishop, White gains space with a central pawn and prepares to undermine Black's pieces.")
v("Open, Bernstein Variation", "White challenges Black's centre knight with the queen's knight at once, aiming to exchange Black's most active piece.")
v("Open, Classical Defense", "Black develops the dark-squared bishop to a modest square, choosing safety and a solid structure over maximum activity.")
v("Open, Italian Variation", "Black puts the dark-squared bishop on its most active diagonal, aimed at White's kingside, accepting sharper play.")
v("Open, Howell Attack", "White develops the queen to pressure Black's queenside pawns and prepare a rook on the d-file.")
v("Open, St. Petersburg Variation", "White challenges Black's centre knight while Black's bishop is active, leading to sharp tactical play around White's kingside.")
v("Open, Dilworth Variation", "Black sacrifices a knight for two pawns and a powerful attack along the open file towards White's king. It is double-edged and very concrete.")

# ---- Closed ----
v("Closed", "Black develops calmly and prepares to castle, choosing the classical closed Spanish. Both sides manoeuvre for a long time before the central break; plans matter more than early tactics.")
v("Closed, Martinez Variation", "White protects the centre pawn with a pawn and delays the classical central setup. It is a modern, flexible system that keeps the game slow and avoids the Marshall gambit.")
v("Closed, Delayed Exchange", "White exchanges the bishop for the knight one move later than in the Exchange Variation, so Black has already committed the bishop to a modest square.")
v("Closed, Breyer Defense", "Black's queen's knight retreats to its starting square to reroute and support the centre, freeing the c-pawn and the light-squared bishop. One of the most respected and solid main lines.")
v("Closed, Breyer", "White strikes in the centre immediately while Black's knight is regrouping.")
v("Closed, Breyer Defense, Zaitsev Hybrid", "Black completes the Breyer knight regrouping. White's typical plan is to bring the queen's knight to the kingside and later decide when to close or open the centre.")
v("Closed, Flohr System", "Black develops the light-squared bishop to the long diagonal to increase pressure on White's centre pawn, as in the Zaitsev.")
v("Closed, Chigorin Defense", "Black's knight attacks the Spanish bishop and goes to the edge to support queenside expansion. Black gains space on the queenside; White keeps the strong centre.")
v("Closed, Zaitsev System", "Black puts pressure on White's centre pawn with the rook and the long-diagonal bishop. Very rich and theoretical; White must watch for counterplay against the centre.")
v("Closed, Bogoljubow Variation", "White strikes in the centre before preventing Black's pin, and Black uses the pin on the knight to increase pressure on White's centre.")
v("Closed, Smyslov Defense", "Black prevents White's minor pieces from using a kingside square before regrouping, a solid prophylactic system.")
v("Closed, Yates Variation", "White breaks in the centre at once without the usual preparatory pawn move on the kingside, allowing Black's pin.")
v("Closed, Smyslov-Breyer-Zaitsev Hybrid", "Black combines the Zaitsev bishop setup with a prophylactic pawn move, a modern flexible way to hold the centre.")
v("Closed, Pilnik Variation", "White protects the centre pawn with a pawn first and sets up the centre slowly, avoiding sharp theory.")
v("Closed, Keres Defense", "In the Chigorin structure Black reroutes the king's knight to support the centre and prepare a kingside pawn advance.")
v("Closed, Kholmov Variation", "Black challenges the Spanish bishop with the light-squared bishop, offering a bishop trade to reduce White's pressure.")
v("Closed, Anti-Marshall", "White avoids the Marshall gambit by attacking Black's advanced queenside pawn first. Black must decide how to protect the queenside before the centre opens.")

# ---- Marshall ----
v("Marshall Attack", "Black sacrifices a centre pawn to open lines and attack White's kingside. White wins a pawn but must defend accurately; Black's compensation is long-lasting activity.")
v("Marshall Attack, Modern Variation", "Black protects the knight with a pawn and keeps the pieces aimed at White's king, the most popular way to continue the Marshall.")
v("Marshall Attack, Main Line", "White strengthens the centre and prepares to defend the kingside light squares while Black's queen and bishops gather for the attack.")
v("Marshall Attack, Modern Main Line", "Black's queen invades near White's king. White blocks the kingside and tries to complete development before Black's attack breaks through.")

# ---- Morphy other ----
v("Morphy Defense", "Black asks the bishop to decide at once. Most strong players retreat it to keep the Spanish pressure; the exchange gives the Exchange Variation.")
v("Morphy Defense, Anderssen Variation", "White protects the centre pawn with a pawn before castling, a calm modern setup that keeps many options and avoids early forcing play.")
v("Morphy Defense, Modern Steinitz Defense", "Black protects the centre pawn with a pawn before developing the king's knight, a solid setup where Black can choose between holding and releasing the centre.")
v("Morphy Defense, Neo-Arkhangelsk Variation", "Black develops the dark-squared bishop actively after gaining queenside space, aiming at White's kingside and the centre. Sharp, modern and very popular among strong players.")
v("Morphy Defense, Steinitz Deferred", "Black protects the centre pawn with a pawn after the knight is out, a solid but slightly passive system that often leads to a kingside fianchetto.")
v("Morphy Defense, Tarrasch Variation", "White develops the queen's knight early to protect the centre pawn, keeping the position simple and flexible.")
v("Morphy Defense, Cozio Defense", "Black develops the king's knight to a modest square to keep the f-pawn free and avoid pins. Unusual but playable.")
v("Morphy Defense, Møller Variation", "Black develops the dark-squared bishop to its most active diagonal before castling, inviting White to build a big centre with gain of time.")
v("Morphy Defense, Arkhangelsk Variation", "Black puts the light-squared bishop on the long diagonal to pressure White's centre pawn, often sacrificing a pawn for activity.")
v("Morphy Defense, Caro Variation", "Black gains queenside space early and drives the bishop back, at the cost of slightly loosening the queenside.")
v("Morphy Defense, Schliemann Defense Deferred", "Black strikes with the f-pawn after first asking the bishop, a sharp gambit-style approach.")
v("Morphy Defense, Classical Defense Deferred", "Black develops the dark-squared bishop actively before the king's knight, aiming at White's kingside and keeping the centre flexible.")

# ---- Schliemann / Classical / others ----
v("Schliemann Defense", "Black strikes at White's centre pawn with the f-pawn at once, a sharp gambit-style defence. White can keep it calm or enter forcing lines where accurate play is essential.")
v("Schliemann Defense, Dyckhoff Variation", "White develops the queen's knight and invites the sharpest lines, where the centre opens quickly.")
v("Schliemann Defense, Tartakower Variation", "Black develops the king's knight to contest the centre after the exchange, aiming for quick development.")
v("Classical Variation", "Black develops the dark-squared bishop to its most active diagonal at once. White usually builds a big centre with gain of time against the bishop.")
v("Classical Variation, Central Variation", "White prepares to build the classical pawn centre, gaining time against Black's active bishop.")
v("Cozio Defense", "Black develops the king's knight to a modest square to avoid pins and keep the f-pawn flexible.")
v("Fianchetto Defense", "Black prepares to develop the dark-squared bishop on the long diagonal, a hypermodern setup that lets White build a big centre.")
v("Bird Variation", "Black offers a knight trade at once. It costs time, and White usually gets a comfortable lead in development.")

# ---- Intros keyed by move path (important unnamed lines and names without an intro above) ----
IP = {}
def p(path, *sentences): IP[path] = list(sentences)
B = "e4 e5 Nf3 Nc6 Bb5 Nf6"
p(B+" d3 Bc5", "Against the quiet protecting move Black develops the dark-squared bishop to its most active diagonal at once. This is the modern main reply at the top level: Black aims the bishop at White's kingside and keeps the option of supporting the centre with a pawn later.")
p(B+" d3 d6", "Black protects the centre pawn with a pawn first and keeps a compact, very solid position. Play is slow; Black often fianchettoes or develops the bishop modestly and waits for White to commit before choosing a plan.")
p(B+" O-O Nxe4 Re1", "Instead of the main pawn move White attacks the knight with the rook at once. Black retreats to a square that questions the bishop, and play heads for an open centre where White regains the pawn but Black's position is very solid.")
p(B+" O-O Nxe4 d4", "The main line: White strikes in the centre to regain the pawn with interest. Black's knight retreats to hit the bishop, and the game usually goes into the famous queenless Berlin endgame or into lines where White keeps the queens.")
p(B+" d3 Bc5 Bxc6", "White gives up the Spanish bishop at once to double Black's pawns, hoping to win the centre pawn or reach a slightly better structure. Black gets the bishop pair and open lines for the pieces in return.")
p(B+" d3 Bc5 c3", "White prepares a central pawn advance and makes a retreat square for the bishop. Black usually castles quickly; the position stays rich and slow, like a closed Italian game with the bishop on the long queenside diagonal.")
p(B+" d3 d6 O-O", "White castles and keeps a flexible setup. Black can choose between a kingside fianchetto, a modest bishop and an early queenside expansion; both sides manoeuvre before any central break.")
p(B+" d3 Bc5 c3 O-O", "Black castles and accepts that White may expand in the centre. A common idea is to meet White's central push with a timely bishop retreat and a counter-strike against White's centre.")
p(B+" O-O Nxe4 Re1 Nd6 Nxe5", "White takes back the centre pawn with the knight, opening the e-file against Black's uncastled king. Black must untangle carefully; the usual plan is to develop the bishop to block the file and castle.")
p(B+" O-O Nxe4 d4 Nd6 Bxc6", "White exchanges the bishop before regaining the pawn. After Black recaptures towards the centre, White takes back material and the queens usually come off, leading to the classical Berlin endgame structure.")
p(B+" d3 Bc5 c3 O-O O-O", "Both sides have castled. White prepares a slow central build-up with the queen's knight and rook, Black keeps the bishop active and prepares a pawn break in the centre or on the queenside.")
p(B+" d3 Bc5 Bxc6 dxc6 Nbd2", "White develops the queen's knight towards the queenside before castling, keeping options to reroute it and to castle on either side. Black's bishop pair and open lines compensate for the damaged pawns.")
p(B+" d3 Bc5 Bxc6 dxc6 O-O", "White castles and plans to target Black's doubled pawns in a slow game. Black usually protects the centre pawn with the knight or queen and uses the bishop pair actively.")
p(B+" O-O Nxe4 Re1 Nd6 Nxe5 Be7", "Black blocks the open file with the bishop and prepares to castle. White retreats the bishop to keep it, and the game becomes an open, symmetrical position where White's lead in development is small but lasting.")
p(B+" d3 Bc5 c3 O-O O-O d6", "Black supports the centre with a pawn, creating a solid classical structure. Typical plans are a queenside pawn expansion for Black and a slow central build-up for White.")
p(B+" O-O Nxe4 Re1 Nd6 Nxe5 Be7 Bf1 Nxe5", "Black exchanges knights to relieve the pressure along the open file. After White recaptures with the rook, Black castles and the position is nearly symmetrical; White plays for a small lasting edge.")
p(B+" O-O Nxe4 d4 Nd6 dxe5 Nxb5 a4 Nbd4", "Black returns the knight to the centre instead of retreating it to the edge. The position becomes concrete: White regains material and Black's pieces must coordinate quickly.")
p(B+" O-O Nxe4 d4 Nd6 Bxc6 dxc6 dxe5 Nf5", "Black's knight takes the best square, and White now trades queens. This is the famous Berlin endgame: Black has lost the right to castle but has the bishop pair and a fortress-like structure.")
p(B+" O-O Nxe4 d4 Nd6 dxe5 Nxb5 a4 Nbd4 Nxd4 d5", "Black strikes in the centre with a pawn to open the bishop's diagonal. The pawn structure becomes unbalanced and both sides have clear targets.")
p(B+" O-O Nxe4 d4 Nd6 dxe5 Nxb5 a4 Nbd4 Nxd4 Nxd4", "Black exchanges knights to simplify. White regains the knight with the queen and keeps central space; Black must develop the bishops quickly.")
p(B+" O-O Nxe4 Re1 Nd6 Nxe5 Be7 Bf1 Nxe5 Rxe5 O-O d4", "White grabs central space with a pawn. Black's usual answer is to develop the bishop to the long diagonal, hitting the rook and the centre; the structure is symmetrical and play is about piece activity.")
p(B+" O-O Nxe4 Re1 Nd6 Nxe5 Be7 Bf1 Nxe5 Rxe5 O-O Nc3", "White develops the queen's knight before committing the centre pawn, keeping flexible options for the bishop and the d-pawn.")
p(B+" O-O Nxe4 d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8 h3", "White's main move in the Berlin endgame: it takes a square away from Black's bishop and knight and prepares kingside expansion. Black usually tucks the king away on the queenside and connects the rooks.")
p(B+" O-O Nxe4 Re1 Nd6 Nxe5 Be7 Bf1 Nxe5 Rxe5 O-O d4 Bf6", "Black's bishop develops actively, attacking White's rook and eyeing the centre. White retreats the rook, and the symmetrical structure gives a long technical game.")
p(B+" O-O Nxe4 Re1 Nd6 Nxe5 Be7 Bf1 Nxe5 Rxe5 O-O d4 Bf6 Re1", "The rook retreats to the open file. White's small lead in development and central pawn give a slight initiative; Black aims to trade the rooks on the open file and equalise.")
p(B+" O-O Nxe4 Re1 Nd6 Nxe5 Be7 Bf1 Nxe5 Rxe5 O-O d4 Bf6 Re1 Re8", "Black contests the open file at once, offering to exchange rooks. Many top-level games here are long technical struggles where precision decides.")
E = "e4 e5 Nf3 Nc6 Bb5 a6"
p(E+" Bxc6 dxc6", "Black recaptures towards the centre, opening lines for the queen and light-squared bishop. White now has the healthy kingside majority; Black has the bishop pair and fast development.")
M = E+" Ba4 Nf6 O-O"
p(M+" Nxe4 d4 b5", "Black drives the bishop away first so that the centre knight can be supported. This is the main road of the Open Ruy Lopez, leading to the classical position where Black keeps the extra centre pawn for a while.")
p(M+" Nxe4 d4 Be7", "Black develops the bishop and prepares to castle before dealing with White's centre, a quieter alternative to the main expansion.")
p(M+" Nxe4 d4 Be7 Re1", "White attacks Black's centre knight along the file at once. Black must decide how to protect it or exchange, and White hopes to exploit the slightly delayed queenside development.")
C = M+" Be7"
p(C+" Re1", "The main line of the Closed Ruy Lopez: White protects the centre pawn with the rook, freeing the knight from its defence. Black usually expands on the queenside to gain space and question the bishop.")
p(C+" Qe2", "White protects the centre pawn with the queen, keeping the rook free for the d-file. It is an old system with the idea of a quick central advance.")
p(C+" Re1 b5", "Black gains queenside space and drives the bishop to its best diagonal, from where it aims at Black's kingside. This is the starting point of most classical closed lines.")
p(C+" d3 b5", "Against the quiet Martinez setup Black still expands on the queenside. White keeps a flexible centre and can choose between slow manoeuvring and an early queenside strike.")
p(C+" Re1 d6", "Black protects the centre pawn with a pawn before expanding on the queenside, keeping a compact structure and avoiding some anti-Marshall ideas.")
p(C+" Bxc6 dxc6 d3", "White protects the centre pawn with a pawn after the delayed exchange. Black has the bishop pair; White plans a slow knight manoeuvre and a kingside majority.")
p(C+" d3 d6 c3", "White builds a solid central structure with pawns and keeps the bishop's retreat. The play resembles a slow Italian game with Spanish ideas.")
p(C+" Re1 b5 Bb3 d6", "Black protects the centre pawn with a pawn, the classical way. White now usually prepares a central advance and protects the bishop's retreat with the c-pawn.")
p(C+" d3 b5 Bb3 d6", "Black supports the centre with a pawn in the Martinez structure. Both sides manoeuvre; White can strike on the queenside with the a-pawn to question Black's pawn chain.")
p(C+" d3 b5 Bb3 O-O", "Black castles first and keeps the option of an early central strike, a flexible move order in the Martinez structure.")
p(C+" Re1 b5 Bb3 Bb7", "Black develops the light-squared bishop to the long diagonal at once, aiming at White's centre and preparing a quick central break.")
p(C+" Qe2 b5 Bb3 O-O", "Black castles in the Worrall setup. White plans a quick central advance supported by the queen, and the rook can go to the d-file.")
p(C+" Re1 b5 Bb3 d6 c3", "White makes room for the bishop and prepares a big pawn centre. Black usually castles next, transposing to the main classical position.")
p(C+" Re1 b5 Bb3 O-O c3", "The main line of the Closed Ruy Lopez: White prepares a central advance and keeps a retreat for the bishop. Black now chooses between the solid classical defence and the Marshall pawn sacrifice.")
p(C+" d3 b5 Bb3 d6 c3", "White keeps the solid Martinez centre and prepares a slow kingside build-up with the queen's knight heading for the kingside.")
p(C+" d3 b5 Bb3 d6 a3", "White makes a retreat square for the bishop and prevents Black's knight from jumping forward on the queenside. A flexible, slow system popular at the top level.")
p(C+" Re1 b5 Bb3 O-O h3", "White prevents Black's light-squared bishop from pinning the knight before deciding on the centre. Black often develops the bishop to the long diagonal in reply.")
p(C+" d3 b5 Bb3 d6 a4", "White strikes at Black's queenside pawn chain at once, trying to open the file for the rook and create weaknesses before Black is fully developed.")
p(C+" d3 b5 Bb3 d6 a3 O-O", "Black castles and completes kingside development. The game becomes a long manoeuvring battle with typical knight rerouting for both sides.")
p(C+" Re1 b5 Bb3 O-O h3 Bb7", "Black develops the bishop to the long diagonal, aiming at White's centre and preparing a central break. White usually answers with a central pawn move that creates direct tension.")
p(C+" d3 b5 Bb3 d6 a4 Bd7", "Black supports the queenside pawn chain with the bishop so that White's pressure on the file does not win anything. The structure stays closed and solid.")
p(C+" d3 b5 Bb3 d6 c3 O-O h3", "White prevents the bishop pin and prepares a slow kingside build-up. Typical plans include rerouting the queen's knight towards the kingside.")
p(C+" Re1 b5 Bb3 O-O c3 d6 h3 Nd7", "The Karpov Variation: Black reroutes the knight to support the centre and free the bishop, preparing a kingside regrouping.")
p(C+" Re1 b5 Bb3 O-O c3 d6 h3 Bb7 d4 Re8 Ng5", "White hits the weak square near Black's king at once, forcing Black's rook back and repeating moves if Black allows. Many games end in a repetition; deviating needs care from both sides.")
p(C+" Re1 b5 Bb3 O-O c3 d6 h3 Nb8 d4 Nbd7 Nbd2", "White completes development and prepares the classical knight manoeuvre towards the kingside. Black's rerouted knight supports the centre; the game is a long strategic battle.")
p(C+" Re1 b5 Bb3 O-O c3 d6 h3 Bb7 d4 Re8 Nbd2", "White develops the queen's knight and prepares to reroute it to the kingside. Black keeps pressure on White's centre and prepares a bishop retreat behind the pawns.")
p(C+" Re1 b5 Bb3 O-O c3 d6 h3 Nb8 d4 Nbd7 Nbd2 Bb7", "Black develops the bishop to the long diagonal, increasing pressure on White's centre. This is the heart of the modern Breyer structure.")
p(C+" Re1 b5 Bb3 O-O c3 d6 h3 Nb8 d4 Nbd7 Nbd2 Bb7 Bc2 Re8", "Black prepares to retreat the bishop behind the pawns and fianchetto it later. White will reroute the knight to the kingside and choose between a central advance and queenside expansion.")
p(C+" Re1 b5 Bb3 O-O c3 d6 h3 Na5 Bc2 c5 d4 Qc7 Nbd2 cxd4 cxd4", "The Chigorin structure with an open c-file: Black uses the file and the queenside space, while White keeps the strong centre and plans a kingside build-up.")
p(C+" Re1 b5 Bb3 O-O c3 d6 h3 Nb8 d4 Nbd7 Nbd2 Bb7 Bc2 Re8 Nf1 Bf8 Ng3 g6", "Black fianchettoes the bishop to protect the king and pressure White's centre. White chooses between a queenside strike with the a-pawn and a central advance.")
A = C+" Re1 b5 Bb3 O-O"
p(A+" a4 Bb7", "Against the queenside strike Black develops the bishop and invites White to keep the tension. Black gives up the Marshall gambit but gets active pieces in the centre.")
p(A+" a4 b4", "Black advances the attacked pawn instead of defending it, gaining queenside space at the cost of a weakened square behind it.")
p(A+" c3 d5 exd5", "White accepts the Marshall gambit pawn. Black now gets long-term attacking chances against White's king in return.")
p(A+" a4 b4 d4", "White strikes in the centre at once, aiming to open lines while Black's queenside pawns are advanced.")
p(A+" a4 Bb7 d3 d6", "Black supports the centre with a pawn in the quiet anti-Marshall structure. The play becomes slow, with manoeuvres on both wings.")
p(A+" c3 d5 exd5 Nxd5", "Black recaptures with the knight and gives up the pawn for activity. White takes the second centre pawn, and Black's pieces flood towards White's kingside.")
p(A+" c3 d5 exd5 Nxd5 Nxe5", "White takes the pawn, the critical test of the Marshall. Black exchanges knights and then brings the pieces towards White's king; theory runs very deep here.")
p(E+" Ba4", "White keeps the pin by retreating the bishop rather than exchanging. This is the main move of the Ruy Lopez and leads to most of the famous systems.")
p(E+" Ba4 Nf6", "Black develops the knight and attacks the centre pawn, the main position of the Ruy Lopez. White most often castles, letting Black choose between the open and closed systems.")
p(E+" Ba4 g6", "Black fianchettoes the dark-squared bishop after questioning the white bishop, aiming for a solid setup that eyes the centre from a distance.")
p(E+" Ba4 Nge7 c3", "Against the Cozio setup White prepares a big centre with pawns. Black usually fianchettoes and tries to hold the centre with pieces.")
p(E+" Ba4 Nge7 O-O", "White castles first and keeps central options. Black continues with a kingside fianchetto or a knight reroute to the kingside.")
p(E+" Ba4 Nf6 d4", "White strikes in the centre at once, offering open lines before castling. Black can take the pawn and must be careful about the e-file.")
p(E+" Ba4 Nf6 Qe2", "White protects the centre pawn with the queen and keeps flexible options for the rook.")
p(E+" Ba4 Nf6 Bxc6", "White exchanges the bishop one move later than in the Exchange Variation, after Black has developed the knight. Black recaptures and has easy development.")
p(E+" Ba4 Nf6 d3 b5", "Against the quiet protecting move Black drives the bishop to the long diagonal first, keeping options for the dark-squared bishop.")
p(E+" Ba4 d6 O-O Bd7", "Black supports the knight with the bishop, breaking the pin and preparing a solid kingside development. White gets a free hand in the centre.")
p(E+" Ba4 Nf6 d3 d6", "Black supports the centre with a pawn and keeps the bishop flexible, aiming for a compact kingside development.")
p(E+" Ba4 Nf6 d3 Bc5", "Black develops the bishop actively against the quiet setup, aiming at White's kingside. Play is slow and positional.")
p(E+" Ba4 Nf6 Nc3 b5", "Against the knight development Black drives the bishop away first, gaining queenside space before deciding on the centre.")
p(E+" Ba4 b5 Bb3 Na5", "Black chases the bishop and offers to trade knight for bishop at once. It is a concrete line where White can try to trap or exploit Black's loose queenside.")
p(E+" Ba4 d6 c3 f5", "Black counter-attacks in the centre with the f-pawn, a sharp idea that opens lines towards White's king at the cost of loosening Black's own.")
p(M+" Bc5 c3", "White prepares a central pawn advance that will hit Black's bishop. Black usually expands on the queenside first to keep the bishop active.")
p(M+" d6 Re1", "White protects the centre pawn with the rook against the solid deferred Steinitz setup, preparing a central advance with the pawns.")
p(E+" Ba4 Nf6 d3 d6 c3", "White builds a solid central pawn structure and keeps a retreat for the bishop. Black often fianchettoes.")
p(E+" Ba4 d6 O-O Bd7 c3", "White prepares a central advance against the solid modern Steinitz setup, with a comfortable space advantage.")
p(E+" Ba4 Nf6 d3 d6 c4", "White grips the centre with pawns, preventing Black's central break. A slow, space-gaining plan.")
p(E+" Ba4 Nf6 d3 b5 Bb3 Bc5", "Black develops the bishop to its most active diagonal after gaining queenside space, a lively modern setup.")
p(M+" Bc5 c3 b5", "Black gains queenside space before White's central advance can hit the bishop, keeping the bishop on its active diagonal.")
p(E+" Ba4 Nf6 d3 d6 c3 g6", "Black fianchettoes the dark-squared bishop to protect the king and pressure the centre from a distance.")
p(E+" Ba4 d6 O-O Bd7 c3 g6", "Black fianchettoes in the modern Steinitz, a solid setup that holds the centre and waits for White to commit.")
p(E+" Ba4 Nf6 d3 b5 Bb3 Be7", "Black develops the bishop modestly and prepares to castle, choosing a solid closed-style setup against the quiet move.")
p(E+" Ba4 d6 c3 Bd7 d4 g6", "Black fianchettoes after White has built the full pawn centre, aiming to pressure it from the long diagonal.")
N = M+" b5 Bb3 Bc5"
p(N+" a4", "White strikes at Black's queenside pawn chain at once, the main test of the active bishop setup. Black usually protects the pawn with the rook.")
p(N+" c3", "White prepares a central pawn advance that will drive back Black's active bishop. Black supports the bishop with a pawn first.")
p(M+" d6 Re1 Bd7 c3", "White prepares a full pawn centre against Black's solid setup. Black often fianchettoes next.")
p(M+" Bc5 c3 b5 Bb3", "The bishop retreats to its best diagonal. Black now chooses between supporting the bishop with a pawn and a sharper central strike.")
p(E+" Ba4 Nf6 d3 d6 c3 g6 O-O", "White castles in the quiet structure; both sides prepare slow manoeuvres before any central break.")
p(N+" a4 Rb8", "Black protects the queenside pawn with the rook, keeping the active bishop. White continues with central or queenside pressure.")
p(N+" c3 d6 d4", "White advances in the centre, hitting the bishop. Black retreats it to a protected square on the diagonal and keeps pressure on the centre.")
p(M+" d6 Re1 Bd7 c3 g6 d4", "White builds the full pawn centre. Black's fianchetto bishop will pressure it while Black keeps the solid centre pawn.")
p(N+" a4 Rb8 c3", "White prepares a central advance while the queenside tension remains. Black supports the bishop with a pawn next.")
p(N+" c3 d6 a4", "White combines the queenside strike with the central preparation, asking Black's queenside pawns to commit.")
p(M+" d6 Re1 Bd7 c3 g6 d4 Bg7 h3", "White prevents any pin and keeps the full centre. A slow maneuvering battle follows, very similar to the classical closed structures.")
p(N+" c3 d6 d4 Bb6 Be3", "White develops the bishop to oppose Black's active bishop, aiming to exchange it and reduce Black's pressure on the centre.")
p(N+" a4 Rb8 c3 d6 d4 Bb6 a5", "White pushes the a-pawn to drive Black's bishop off its diagonal and gain queenside space.")
p(M+" d6 Re1 Bd7 c3 g6 d4 Bg7 h3 O-O Bc2", "White retreats the bishop to support the centre and protect the king's diagonal. A typical slow closed-style position.")
p(N+" a4 Rb8 c3 d6 d4 Bb6 a5 Ba7 h3", "White prevents the bishop pin and keeps all options. Black's bishop is awkwardly placed but still eyes White's kingside.")
p("e4 e5 Nf3 Nc6 Bb5 f5 d3", "White meets the Schliemann calmly, protecting the centre pawn and keeping a solid position. Black's f-pawn break has less punch, and White aims to exploit the loosened black kingside.")
p(E+" Ba4 Bc5 c3", "White prepares a central pawn advance that will hit Black's active bishop. Black usually develops the knight to its alternative square to keep the centre supported.")
p(E+" Ba4 Bc5 O-O", "White castles first and keeps the central advance in reserve. Black develops the king's knight towards the kingside.")
p(E+" Ba4 Bc5 O-O Nge7", "Black develops the knight to a square from which it supports the centre and avoids pins, a flexible idea against the castled king.")
p(E+" Ba4 Bc5 c3 Nge7 d4", "White builds the full centre with tempo on the bishop. Black must decide whether to take or keep the tension.")
p("e4 e5 Nf3 Nc6 Bb5", "The Ruy Lopez: White develops the bishop to attack the knight that protects Black's centre pawn. Its pressure is slow but lasting, and it has been a main opening at every level for centuries.")
p("e4 e5 Nf3 Nc6 Bb5 Nge7 Nc3", "Against the Cozio setup White develops naturally and keeps central options. Black usually reroutes the knight to the kingside.")
p("e4 e5 Nf3 Nc6 Bb5 Nge7 Nc3 Ng6", "Black's knight goes to the kingside, supporting the centre pawn and freeing the bishop. White aims for a quick central break.")
