# WINPLAN claims: each named move must be one of that side's statistically distinctive winning moves (checked).
P = {}
def w(path, text, *moves): P.setdefault(path, {}).setdefault("white", []).append({"type": "WINPLAN", "text": text, "moves": list(moves)})
def b(path, text, *moves): P.setdefault(path, {}).setdefault("black", []).append({"type": "WINPLAN", "text": text, "moves": list(moves)})
B = "e4 e5 Nf3 Nc6 Bb5 Nf6"
R = B + " O-O Nxe4"
w(R, "White's wins here mostly came through the queenless endgame: Bxc6 and the queen trade Qxd8 lead to positions where White develops with Nc3 and h3, puts a rook on Rd1 and brings the knight to Ne4 to press with the healthy kingside majority.", "Bxc6", "Qxd8", "Nc3", "h3", "Rd1", "Ne4")
b(R, "Black's winners completed development quickly with the bishop on Be6, contesting the light squares and connecting the rooks.", "Be6")
w(B+" d3 Ne7", "White's winners kept the bishop with Ba4, developed with Nc3 and Be3, and used the jump Ng5 to probe Black's kingside.", "Ba4", "Nc3", "Be3", "Ng5")
w(R+" d4", "In the endgame lines White's winning plan is the kingside majority: f4 and g4 push forward to create a passed pawn, with a knight on Ne4 or Nh4 supporting the advance.", "f4", "g4", "Ne4", "Nh4")
b(R+" d4", "Black's winners built a solid shelter with b6 and played h6 to keep White's pieces away from the kingside, then used the bishop pair once lines opened.", "b6", "h6")
b(B+" d3 Bc5 Bxc6", "Black's winners often castled long with O-O-O and used the kingside pawns, starting with g6, to attack White's castled king.", "O-O-O", "g6")
b(B+" d3 d6 O-O", "Black's winners rerouted the knight with Ne7 towards the kingside, contested the light squares with Be6 and struck at White's centre with the f-pawn advance f5.", "Ne7", "Be6", "f5")
b(R+" d4 Nd6", "Black's winners built the classic Berlin endgame setup with b6, securing the king's shelter on the queenside and preparing to use the bishop pair.", "b6")
w(R+" d4 Nd6 dxe5", "White's winners gained queenside space with a5 and b4, lifted the rook with Ra3 to swing it across, and supported the centre pawn with Re1, c3 and sometimes f3 after Nd2.", "a5", "b4", "Ra3", "Re1", "c3", "f3", "Nd2")
b(R+" d4 Nd6 dxe5", "Black's winners developed with Be6 and Bd6, challenged the queenside with b6 and placed a knight on Ne5 once White's centre pawn had gone.", "Be6", "Bd6", "b6", "Ne5")
w(R+" d4 Nd6 Bxc6", "White's winning plan in this endgame is the kingside majority: the f-pawn advance f4 starts the march towards a passed pawn.", "f4")
b(R+" d4 Nd6 Bxc6", "Black's winners tucked the king away with Kc8 and gained queenside space with a5; when the queenside was settled, the king sometimes went the other way with Ke7 to blockade White's majority.", "Kc8", "a5", "Ke7")
w(B+" d3 Bc5 c3 O-O O-O", "White's winners kept the Spanish bishop by retreating it to Bc2, where it supports the centre and aims at Black's king.", "Bc2")
w(B+" d3 Bc5 Bxc6 dxc6 Nbd2", "White's winners used the jump Ng5 to pressure Black's kingside before Black had organised it.", "Ng5")
b(B+" d3 Bc5 Bxc6 dxc6 Nbd2", "Black's winners castled long with O-O-O and used queenside space with b5, using the bishop pair against White's king.", "O-O-O", "b5")
b(B+" d3 Bc5 Bxc6 dxc6 O-O", "Black's winning recipe is a direct attack: the bishop pins the knight and stays on Bh5, Black castles long with O-O-O, the queen comes to Qe7 and the kingside pawns storm with h6 and g5 against White's castled king.", "Bh5", "O-O-O", "Qe7", "h6", "g5")
w(R+" d4 Nd6 Ba4", "White's winners developed rapidly with Qd3 and Bg5, using the lead in development against Black's uncastled king.", "Qd3", "Bg5")
b(B+" d3 Bc5 c3 O-O O-O d6", "Black's winners expanded on the queenside with a6 and b5 and rerouted the knight to Nf4, a strong square in front of White's king.", "a6", "b5", "Nf4")
X = R+" Re1 Nd6 Nxe5 Be7 Bf1 Nxe5"
w(X, "White's winners developed the knight with Nc3 and jumped it to Nd5, where it presses on Black's bishop and the dark squares.", "Nc3", "Nd5")
b(R+" d4 Nd6 Bxc6 dxc6 dxe5 Nf5", "Black's winners walked the king to safety with Kc8 and Kb7 and gained queenside space with a4, fixing White's queenside pawns.", "Kc8", "Kb7", "a4")
w(R+" d4 Nd6 Bxc6 dxc6 dxe5 Nf5", "White's winners pushed the kingside majority with f4, aiming for a passed pawn while Black's king is far away.", "f4")
b(R+" d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8", "Black's winners walked the king to Kc8 and Kb7, gained space with b5 or a4 and only then used the bishop pair to open lines.", "Kc8", "Kb7", "b5", "a4")
w(X+" Rxe5 O-O d4", "White's winners developed with Nc3 and jumped into Nd5, the key square in this symmetrical structure.", "Nc3", "Nd5")
w(X+" Rxe5 O-O Nc3", "White's winners gained queenside space with a4 and kept the bishop flexible on Bd3.", "a4", "Bd3")
w(R+" d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8 h3", "White's winning plan is the kingside majority: the f-pawn advance f4, prepared by the knight on Ne4 or Nc3, creates a passed pawn.", "f4", "Ne4", "Nc3")
b(R+" d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8 h3", "Black's winners played b6 with the king to Kc8 and Kb7, gained queenside space with a5 and a4, and rerouted the knight with Ne7 when White's kingside pawns advanced.", "b6", "Kc8", "Kb7", "a5", "a4", "Ne7")
w(X+" Rxe5 O-O d4 Bf6", "White's winners developed with Nc3, jumped into Nd5 to exchange or harass Black's bishop, and pinned with Bg5.", "Nc3", "Nd5", "Bg5")
w(X+" Rxe5 O-O d4 Bf6 Re1", "White's winners played Nc3 and Nd5 against Black's bishop and added Bg5 to increase pressure on the dark squares.", "Nc3", "Nd5", "Bg5")
b(X+" Rxe5 O-O d4 Bf6 Re1", "Black's winners played on the queenside with b6 and a5, kept the knight active and used h6 to stop White's bishop from pinning.", "b6", "a5", "h6")
w(X+" Rxe5 O-O d4 Bf6 Re1 Re8", "White's winners centralised with Nc3 and Nd5, pinned with Bg5 and sometimes added Qe4 or the f-pawn advance f4 for kingside pressure.", "Nc3", "Nd5", "Bg5", "Qe4", "f4")
b(X+" Rxe5 O-O d4 Bf6 Re1 Re8", "Black's winners gained queenside space with a5 and b6, supported the centre with d6 and developed with Be6.", "a5", "b6", "d6", "Be6")
EX = "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6 dxc6"
w(EX+" O-O", "White's winners prepared the central pawn break with c3, aiming to open the position only when the kingside majority is ready.", "c3")
b(EX+" Nc3", "Black's winners rerouted the king's knight via Ne7 and Ng6, sometimes to Ne5, and developed the bishop to Be7 behind it.", "Ne7", "Ng6", "Ne5", "Be7")
w(EX+" O-O f6", "White's winners put the rook on Re1 and regrouped the knight with Nd2, preparing to open lines against Black's slightly loose kingside.", "Re1", "Nd2")
O = "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Nxe4 d4"
w(O+" b5", "White's winners rerouted the queen's knight via Nf1 towards the kingside, the classic manoeuvre against Black's centre pieces.", "Nf1")
w(O+" Be7", "White's winners developed the dark-squared bishop to Be3 and used a rook lift Re3 to bring more pieces to the kingside.", "Be3", "Re3")
b(O+" Be7", "Black's winners activated the queen with Qh4 and used the h-pawn advance h5 for kingside play.", "Qh4", "h5")
w(O+" Be7 Re1", "White's winners opened the centre with dxe5, developed with Be3 and lifted the rook with Re3.", "dxe5", "Be3", "Re3")
b(O+" Be7 Re1", "Black's winners placed the bishop on Bd6 or Bf6, activated the queen with Qh4 and supported the centre with c6.", "Bd6", "Bf6", "Qh4", "c6")
w(O+" b5 Bb3 d5 dxe5 Be6", "White's winners rerouted the queen's knight via Nf1 towards the kingside, attacking Black's centre pieces.", "Nf1")
b(O+" b5 Bb3 d5 dxe5 Be6", "Black's winners kept the bishop active on Bf5, controlling the light squares in front of White's centre.", "Bf5")
b(O+" b5 Bb3 d5 dxe5 Be6 Nbd2", "Black's winners kept the bishop active on Bf5, won the bishop pair by taking on Nxb3, gained space with a5 and sometimes castled long with O-O-O.", "Bf5", "Nxb3", "a5", "O-O-O")
w(O+" b5 Bb3 d5 dxe5 Be6 Nbd2", "White's winners developed the bishop actively with Bg5, pressing against Black's centre and kingside.", "Bg5")
w(O+" b5 Bb3 d5 dxe5 Be6 Qe2", "White's winners prepared with c3 and centralised the knight on Nd4.", "c3", "Nd4")
w(O+" b5 Bb3 d5 dxe5 Be6 c3 Be7", "White's winners played for the kingside: Qd3 and Bf4, with the bold pawn advance g4 in some games.", "Qd3", "Bf4", "g4")
b(O+" b5 Bb3 d5 dxe5 Be6 c3 Be7", "Black's winners gained queenside space with a5 and pushed the d-pawn as far as d3, cramping White's development.", "a5", "d3")
w(O+" b5 Bb3 d5 dxe5 Be6 c3 Bc5", "White's winners rerouted the knight via Nf1 to Ne3 and kept the bishop on Bb3 to press on Black's centre.", "Nf1", "Ne3", "Bb3")
b(O+" b5 Bb3 d5 dxe5 Be6 c3 Bc5", "Black's winners activated the queen with Qd6, struck with c5 and put a knight on Ne5.", "Qd6", "c5", "Ne5")
w(O+" b5 Bb3 d5 dxe5 Be6 c3 Bc5 Nbd2", "White's winners kept the bishop on Bb3 and used the rook on Re1 against Black's centre.", "Bb3", "Re1")
C = "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7"
b(C+" d3 d6 c3", "Black's winners regrouped Breyer-style with Nb8, supported the centre with c6, put the bishop on Bb7 and gained queenside space with a5.", "Nb8", "c6", "Bb7", "a5")
w(C+" d3 d6 c3", "White's winners pinned the knight with Bg5, increasing pressure on Black's centre.", "Bg5")
w(C+" d3 b5 Bb3 O-O", "White's winners developed the dark-squared bishop to Be3 to challenge Black's active pieces.", "Be3")
w(C+" Re1 b5 Bb3 Bb7", "White's winners met Black's early bishop with Nc3 and the central break d4; after cxd4 White's centre is strong and the knight can jump to Nd5.", "Nc3", "d4", "cxd4", "Nd5")
w(C+" Re1 b5 Bb3 O-O c3", "White's winners often closed the centre with d5 and then played on the kingside, with the bishop on Be3.", "d5", "Be3")
b(C+" Re1 b5 Bb3 O-O c3", "Black's winners gained queenside space with c5.", "c5")
w(C+" d3 b5 Bb3 d6 c3", "White's winners pinned the knight with Bg5 to increase pressure on Black's centre.", "Bg5")
b(C+" d3 b5 Bb3 d6 c3", "Black's winners developed the bishop to Be6 to challenge White's Spanish bishop.", "Be6")
b(C+" d3 b5 Bb3 d6 a3", "Black's winners played h6 early to keep White's bishop and knight away from the squares in front of Black's king.", "h6")
b(C+" d3 b5 Bb3 d6 a4", "Black's winners rerouted the knight with Ne7 towards the kingside.", "Ne7")
w(C+" Re1 b5 Bb3 O-O h3 Bb7", "White's winners kept the bishop on Ba2 and brought the knight to Ng3 for a kingside build-up.", "Ba2", "Ng3")
b(C+" d3 b5 Bb3 d6 c3 O-O h3", "Black's winners played g6 to prepare a kingside regrouping, developed with Be6 and gained queenside space with a5.", "g6", "Be6", "a5")
b(C+" Re1 b5 Bb3 O-O c3 d6 d4", "Black's winners regrouped with Nd7, opened the c-file with cxd4 and strengthened the kingside with g6.", "Nd7", "cxd4", "g6")
w(C+" Re1 b5 Bb3 O-O d3 d6 c3", "White's winners developed with Be3 and then launched the f-pawn with f4 against Black's kingside.", "Be3", "f4")
K = C+" Re1 b5 Bb3 O-O c3 d6 h3"
b(K+" Nb8", "Black's winners gained queenside space with the pawn advance c4, cramping White's queenside and freeing squares for the knights.", "c4")
b(K+" Nb8 d4", "Black's winners gained queenside space with the pawn advance c4, cramping White's queenside.", "c4")
b(K+" Nb8 d4 Nbd7", "Black's winners gained queenside space with the pawn advance c4, cramping White's queenside.", "c4")
w(K+" Re8", "White's winners kept the bishop on Ba2 and the queen on Qc2, building up slowly before opening the centre.", "Ba2", "Qc2")
b(K+" h6", "Black's winners rerouted the knights with Nb8 and Ng6, and put the bishop on Bb7.", "Nb8", "Ng6", "Bb7")
w(K+" h6", "White's winners played b3 and c4 to gain queenside space and restrict Black's knights.", "b3", "c4")
w(K+" Nb8 d4 Nbd7 Nbd2", "White's winners struck on the queenside with c4, opening lines where they are stronger.", "c4")
b(K+" Nb8 d4 Nbd7 Nbd2", "Black's winners advanced b4 to gain queenside space and fix White's pawns.", "b4")
w(K+" Nb8 d4 Nbd7 Nbd2 Bb7", "White's winners struck on the queenside with c4.", "c4")
b(K+" Nb8 d4 Nbd7 Nbd2 Bb7", "Black's winners advanced b4 to gain queenside space.", "b4")
w(K+" Nb8 d4 Nbd7 Nbd2 Bb7 Bc2 Re8", "White's winners struck on the queenside with c4, opening lines there.", "c4")
b(K+" Nb8 d4 Nbd7 Nbd2 Bb7 Bc2 Re8", "Black's winners advanced b4 to gain queenside space and fix White's pawns.", "b4")
b(K+" Bb7 d4 Re8 Nbd2", "Black's winners put the queen on Qc7 and the rook on Rb8, preparing queenside play.", "Qc7", "Rb8")
w(K+" Nb8 d4 Nbd7 Nbd2 Bb7 Bc2 Re8 Nf1 Bf8 Ng3 g6", "White's winners struck on the queenside with c4 and put a rook on Rd1 to support the centre.", "c4", "Rd1")
b(K+" Nb8 d4 Nbd7 Nbd2 Bb7 Bc2 Re8 Nf1 Bf8 Ng3 g6", "Black's winners gained queenside space with c4 and a5.", "c4", "a5")
A = C+" Re1 b5 Bb3 O-O"
b(A+" a4 b4", "Black's winners took on bxc3 when White challenged the advanced pawn, opening the b-file for the rook, and put the queen on Qd7.", "bxc3", "Qd7")
b(A+" c3 d5", "Black's winners attacked with the classic Marshall pattern: the queen to Qh5 and the bishop to Bh3, aiming at White's castled king on the light squares.", "Qh5", "Bh3")
b(A+" c3 d5 exd5", "Black's winners attacked with the queen on Qh5 and the bishop on Bh3 against White's king.", "Qh5", "Bh3")
w(A+" c3 d5 exd5", "White's winners completed development with Be3, covering the dark squares, and used the open file with Re8 once the attack was neutralised.", "Be3", "Re8")
b(A+" a4 b4 d4", "Black's winners struck back with c5, opened lines with bxc3 and supported the centre with Re8 and h6.", "c5", "bxc3", "Re8", "h6")
w(A+" a4 b4 d4", "White's winners pinned with Bg5 and placed the bishop on Bd5 in the centre.", "Bg5", "Bd5")
b(A+" c3 d5 exd5 Nxd5", "Black's winners attacked with the queen on Qh5 and the bishop on Bh3 against White's king.", "Qh5", "Bh3")
b(A+" c3 d5 exd5 Nxd5 Nxe5", "Black's winners attacked with Qh5 and Bh3, adding the f-pawn advance f5 to bring the rook into the attack.", "Qh5", "Bh3", "f5")
MA = A+" c3 d5 exd5 Nxd5 Nxe5 Nxe5 Rxe5 c6"
b(MA, "Black's winners threw the f-pawn forward with f5 and f4, kept Bh3 and Qh5 aimed at White's king, and often played Kh8 first to make the f-pawn advance safe.", "f5", "f4", "Bh3", "Qh5", "Kh8")
w(MA, "White's winners completed development with Be3 and later used the open file with Re8 once Black's attack was neutralised.", "Be3", "Re8")
b(MA+" d4", "Black's winners played Kh8 and pushed the f-pawn with f5 and f4, with the bishop on Bh3 supporting the attack.", "Kh8", "f5", "f4", "Bh3")
b(MA+" d4 Bd6 Re1 Qh4 g3 Qh3", "Black's winners played Kh8 and pushed the f-pawn with f5 and f4, with the bishop on Bh3 supporting the attack.", "Kh8", "f5", "f4", "Bh3")
M = "e4 e5 Nf3 Nc6 Bb5 a6 Ba4"
b(M+" Nge7 c3", "Black's winners pinned the knight with Bg4 and castled long with O-O-O.", "Bg4", "O-O-O")
w(M+" Nge7 O-O", "White's winners closed the centre with d5 to cramp Black's pieces.", "d5")
b(M+" Nf6 d4", "Black's winners struck back in the centre with d5.", "d5")
b(M+" Nf6 Qe2", "Black's winners chased the bishop with b5, traded it with Na5 and put the bishop on Bb7.", "b5", "Na5", "Bb7")
b(M+" Nf6 Bxc6", "Black's winners castled long with O-O-O, pinned with Bg4 and stormed with h5 and g5 against White's king.", "O-O-O", "Bg4", "h5", "g5")
b(M+" Nf6 d3 d6", "Black's winners struck at White's centre with the f-pawn advance f5.", "f5")
w(M+" d6 c3 f5", "White's winners exploited the light squares weakened by Black's f-pawn: the bishop returned to Bb3 and the queen came to Qb3 or Qd5.", "Bb3", "Qb3", "Qd5")
w(M+" Nf6 d3 d6 c4", "White's winners exchanged with Bxc6 and prepared d4 with b3 to open the centre.", "Bxc6", "b3", "d4")
b(M+" Nf6 d3 d6 c4", "Black's winners occupied the hole in White's camp with Nd4, which White's pawns can no longer drive away.", "Nd4")
w(M+" Nf6 d3 b5 Bb3 Bc5", "White's winners pinned the knight with Bg5 and kept the pin with Bh4, retreating to Bg3 when needed.", "Bg5", "Bh4", "Bg3")
w(M+" Nf6 O-O b5 Bb3 Bb7", "White's winners blunted Black's long-diagonal bishop by closing the centre with d5, keeping the bishop on Bc2.", "d5", "Bc2")
b(M+" Nf6 d3 d6 c3 g6", "Black's winners played c5 and the f-pawn advance f5.", "c5", "f5")
b(M+" d6 O-O Bd7 c3 g6", "Black's winners prepared the f-pawn advance f5 with the queen on Qe8.", "f5", "Qe8")
b(M+" Nf6 d3 b5 Bb3 Be7", "Black's winners regrouped with Nd7 and Bf8, a Breyer-style setup.", "Nd7", "Bf8")
b(M+" Nf6 d3 d6 c3 g6 O-O", "Black's winners played c5 and the f-pawn advance f5.", "c5", "f5")
w("e4 e5 Nf3 Nc6 Bb5 f5", "White's winners used the knight on Nd5, a central outpost that Black's f-pawn advance no longer controls.", "Nd5")
b("e4 e5 Nf3 Nc6 Bb5 Bc5 c3", "Black's winners kept the bishop safe with Ba7, developed with Bd7, rerouted the knight to Ng6 and used the rook on Re8.", "Ba7", "Bd7", "Ng6", "Re8")
w(M+" Bc5 O-O", "White's winners rerouted the queen's knight via Nf1 to Ng3 for kingside play.", "Nf1", "Ng3")
w(M+" Bc5 O-O Nge7", "White's winners rerouted the queen's knight via Nf1 to Ng3 for kingside play.", "Nf1", "Ng3")
w("e4 e5 Nf3 Nc6 Bb5 Nge7 Nc3", "White's winners used the knight jump Nd5 to exploit Black's slow development.", "Nd5")
b("e4 e5 Nf3 Nc6 Bb5 Nge7 Nc3", "Black's winners pinned with Bg4 and used the rook on Re8.", "Bg4", "Re8")
